spring.application.name=localservice

# # H2 Database connection (Local Development)
# spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.h2.console.enabled=true

# MySQL connection (Commented out for now)
spring.datasource.url=jdbc:mysql://localhost:3306/local_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=19161
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server config
server.port=8080

# Twilio Configuration
twilio.account.sid=YOUR_TWILIO_ACCOUNT_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.whatsapp.number=whatsapp:+14155238886

# ==========================================
# MAIL CONFIGURATION
# ==========================================

# # OPTION 1: MOCK EMAIL (Log OTP to terminal console)
# spring.mail.username=your_email@gmail.com

# # OPTION 2: REAL GMAIL SMTP (Uncomment below to use)
# # NOTE: If authentication fails, generated a NEW App Password from Google.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karthielango.2006@gmail.com
spring.mail.password=gvhpjzliqtewvnrf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.enable=false




